# Generated by Django 4.2.4 on 2023-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("random_events_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dice_d6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Random100",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
